
export const disposableDomains = new Set([
    "10minutemail.com",
    "10minutemail.net",
    "10minutemail.org",
    "guerrillamail.com",
    "guerrillamailblock.com",
    "guerrillamail.net",
    "guerrillamail.org",
    "sharklasers.com",
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    "mailinator.com",
    "temp-mail.org",
    "temp-mail.ru",
    "temp-mail.info",
    "tempmail.com",
    "tempmail.net",
    "tempmail.org",
    "tempmail.us",
    "tempr.email",
    "throwawaymail.com",
    "getnada.com",
    "abnama.com",
    "dispostable.com",
    "mailnes.com",
    "maildrop.cc",
    "mailpoof.com",
    "mintemail.com",
    "trashmail.com",
    "trashmail.net",
    "trashmail.org",
    "uroid.com",
    "urhen.com",
    "rmqkr.net",
    "journeyz.net",
    "superrito.com",
    "teleworm.us",
    "armyspy.com",
    "cuvox.de",
    "dayrep.com",
    "einrot.com",
    "fleckens.hu",
    "gustr.com",
    "jourrapide.com",
    "rhyta.com",
    "wigner.com",
    "wokmail.com",
    "emailondeck.com",
    "tempmailo.com",
    "temp-mail.io",
    "nctime.com",
    "luxusmail.xyz",
    "teewee.eu",
    "the20something.com",
    "moakt.com",
    "mail.tm",
    "inbox.testmail.app",
    "mailv.co",
    "my10minutemail.com",
    "20minutemail.com",
    "guerrillamail.biz",
    "guerrillamail.de",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamailblock.com",
    "pokemail.net",
    "spam4.me",
    "grr.la",
    "sharklasers.com",
    "guerramail.com",
    "kep.im"
]);

export const isDisposableEmail = (email: string): boolean => {
    if (!email) return false;

    const domain = email.split('@')[1];
    if (!domain) return false;

    return disposableDomains.has(domain.toLowerCase());
};
