create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  image_url text,
  author text not null,
  category text not null,
  status text not null default 'Draft',
  views integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  published_at timestamp with time zone
);

-- Enable RLS
alter table public.blogs enable row level security;

-- Create policies
DROP POLICY IF EXISTS "Public blogs are viewable by everyone" ON public.blogs;
create policy "Public blogs are viewable by everyone"
  on public.blogs for select
  using ( status = 'Published' );

DROP POLICY IF EXISTS "Admins can do everything" ON public.blogs;
create policy "Admins can do everything"
  on public.blogs for all
  using ( auth.jwt() ->> 'email' = 'sharma.priyanshu3434@gmail.com' )
  with check ( auth.jwt() ->> 'email' = 'sharma.priyanshu3434@gmail.com' );
