name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from your private org repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Vercel CLI on the GitHub Action runner
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Step 3: Fetch project setting parameters from Vercel
      - name: Pull Vercel Environment Information
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}



      # Step 4: Deploy to Vercel (Vercel will handle the build automatically)
      - name: Deploy to Vercel
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --yes --token=${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

